name: Build Docker Image with Metadata

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Parse metadata from file
    #   id: metadata
    #   run: |
    #     VERSION=$(jq -r '.version' metadata.json)
    #     BUILD_DATE=$(jq -r '.build_date' metadata.json)
    #     AUTHOR=$(jq -r '.author' metadata.json)
    #     echo "IMAGE_VERSION=$VERSION" >> $GITHUB_OUTPUT
    #     echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_OUTPUT
    #     echo "IMAGE_AUTHOR=$AUTHOR" >> $GITHUB_OUTPUT
    #   shell: bash
    - name: Parse package labels from .csproj
      id: csproj_labels
      run: |
        labels=$(grep -oP '<PackageReference Include="\K[^"]+' SEM.NG.DataQuery.Service.csproj | paste -sd "," -)
        echo "PACKAGE_LABELS=$PACKAGE_LABELS" >> $GITHUB_OUTPUT
      shell: bash

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: amrita269
        password: Amrita123@@

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: amrita269/my-docker-app:latest
        build-args: |
          PACKAGE_LABELS=${{ steps.metadata.outputs.PACKAGE_LABELS}}
          # BUILD_DATE=${{ steps.metadata.outputs.BUILD_DATE }}
          # IMAGE_AUTHOR=${{ steps.metadata.outputs.IMAGE_AUTHOR }}
          # PACKAGE_LABELS=${{ steps.csproj_labels.outputs.PACKAGE_LABELS }}
