name: Build Docker Image with Metadata

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Parse metadata from file
      id: metadata
      run: |
        VERSION=$(jq -r '.version' metadata.json)
        BUILD_DATE=$(jq -r '.build_date' metadata.json)
        AUTHOR=$(jq -r '.author' metadata.json)
        echo "IMAGE_VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_OUTPUT
        echo "IMAGE_AUTHOR=$AUTHOR" >> $GITHUB_OUTPUT
      shell: bash

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: amrita269
        password: Amrita123@@

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Build context is the current directory
        push: true # Push the image to the registry
        tags: amrita269/my-docker-app:latest
        build-args: |
          IMAGE_VERSION=${{ steps.metadata.outputs.IMAGE_VERSION }}
          BUILD_DATE=${{ steps.metadata.outputs.BUILD_DATE }}
          IMAGE_AUTHOR=${{ steps.metadata.outputs.IMAGE_AUTHOR }}
